- name: Клонирование репозитория
  hosts: web
  become: true
  tasks:
    - name: Клонировать приложение
      ansible.builtin.git:
        repo: "https://github.com/DavyRoy/DevOps_practick.git"
        dest: /home/vagrant/app

    - name: Сборка Docker-образа
      community.docker.docker_image:
        name: demo-backend
        source: build
        build:
          path: /home/vagrant/app/Ansible/DOCKER-ANS-05
        state: present

    - name: Запуск контейнера
      community.docker.docker_container:
        name: demo-backend
        image: demo-backend
        state: started
        restart_policy: always
        published_ports:
          - 8090:3000

    - name: Проверка состояния доступности
      uri:
        url: "http://localhost:8090"
        return_content: yes
      register: result

    - name: Добавить SSH-ключ
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
