pipeline {
  agent any

  stages {
    stage('Git') {
      steps {
        checkout scm
        echo 'Репозиторий загружен.'
      }
    }
    stage('Build') {
      steps {
        sh 'echo "CI выполняется..."'
      }
    }
  }
}
