#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/nginx
- name: Установка пакетов nginx
  apt:
    name: "{{ package_name }}"
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - nginx
    - install
    - packages
