name: Docker Release

on:
  push:
    branches:
      - main  # только при пуше в main

jobs:
  docker-release:
    name: 🐳 Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      # 2. Настраиваем Docker Buildx
      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Авторизация в DockerHub
      - name: 🔐 Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Сборка образа (без публикации)
      - name: 🛠️ Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: yourusername/appname:latest
          outputs: type=docker  # локальный образ для следующего шага

      # 👉 Место для вставки проверки или echo
      - name: ✅ Проверка после сборки
        run: echo "Образ успешно собран. Переходим к публикации..."

      # 5. Публикация образа
      - name: 📤 Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: yourusername/appname:latest
