- name: Установка nginx через роль
  hosts: web
  become: true
  roles:
    - role: nginx
      tags: [install, config]
- name: Установка Docker и запуск тест-контейнера
  hosts: docker
  become: true
  roles:
    - role: docker
      tags: [docker]
