all:
  children:
    web:
      hosts:
        web1:
          ansible_host: 10.37.129.4
          ansible_user: vagrant
          ansible_ssh_private_key_file: /Users/sergeylapshov/Documents/Devops/docker/Ansible/.vagrant/machines/default/parallels/private_key
