pipeline {
    agent {
    docker {
      image 'docker:24.0.7'
      args '-v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t myapp:latest .'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'docker run --rm myapp:latest ./run-tests.sh'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                  docker rm -f myapp_container || true
                  docker run -d --name myapp_container -p 8080:80 myapp:latest
                '''
            }
        }
    }

    post {
        always {
            script {
                echo "🧹 Удаляем контейнер myapp_container если он был"
                sh 'docker rm -f myapp_container || true'
            }
        }
    }
}
