pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git '...'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t myapp:latest .'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'docker run --rm myapp:latest ./run-tests.sh'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker run -d -p 80:80 myapp:latest'
            }
        }
    }
}
