- name: Установка пакетов
  hosts: web
  become: true

  tasks:
    - name: Установка пакетов nginx
      apt:
        name: "{{ package_name }}"
        state: present

- name: Установка пакетов
  hosts: db
  become: true

  tasks:
    - name: Установка пакетов postgres
      apt:
        name: "{{ package_name }}"
        state: present

