Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.provider "parallels" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.network "private_network", type: "dhcp"
  config.vm.hostname = "ubuntu-node"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y python3 python3-pip
  SHELL
end
