name: Deploy via Ansible

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: 📂 Добавить приватный ключ
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Подключение к серверу и запуск Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook Ansible/DOCKER-ANS-07/deploy.yml --private-key .ssh/id_rsa

      - name: 📬 Telegram Notification (success)
        if: success()
        run: |
          MESSAGE="✅ УСПЕХ%0AПроект: *${{ github.event.repository.name }}*%0AВетка: *${{ github.ref_name }}*%0A[Пайплайн](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="$MESSAGE" \
            -d parse_mode=Markdown

      - name: ⚠️ Telegram Notification (failure)
        if: failure()
        run: |
          MESSAGE="❌ ОШИБКА%0AПроект: *${{ github.event.repository.name }}*%0AВетка: *${{ github.ref_name }}*%0A[Пайплайн](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="$MESSAGE" \
            -d parse_mode=Markdown
