name: Deploy Docker

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via custom action
        uses: ./.github/actions/deploy
